apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app-deployment
  labels:
    app: shopping-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: shopwebsite
        image: rahulpoojar/shoppingapp:v1
        ports:
        - containerPort: 5173
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
