apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-app-hpa
  namespace: shopping-app

spec:
  scaleTargetRef:
    kind: Deployment
    name: shopping-app-deployment
    apiVersion: apps/v1

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 35 # If pod uses 35% CPU, then scale
